#!/usr/bin/env ruby

require 'goliath/runner'
require File.expand_path(File.dirname($0),'bud_endpoint')  #'bud_endpoint/bud_endpoint.rb'

# set default run options
runner = Goliath::Runner.new(ARGV, BudEndpoint.new)
runner.port = nil
runner.address = File.expand_path(File.join(File.dirname($0),'..','shared','sockets','bud_endpoint.sock'))
runner.log_file = File.expand_path(File.join(File.dirname($0),'..','shared','logs','bud_endpoint.log'))
runner.app = Goliath::Rack::Builder.build(BudEndpoint, runner.api)
runner.run
